describe ('User can delete a contact', () => {
    it('by clicking the delete button', () => {
        cy.visit('http://localhost:3001')
        cy.get('#add-contact').click()
        cy.get('#name').type('Emma')
        cy.get('#email').type('emma@mail.com')
        cy.get('#phone').type('070 1234567')
        cy.get('#company').type('Craf Academy')
        cy.get('#notes').type('Struggling noob coder')
        cy.get('#twitter').type('@emma')
        cy.get('#submit').click()
        cy.wait(500)
        cy.get('#delete-button').click()
        cy.contains('thomas@craft.se').should('not.exist')
    })
})