describe ('update a contact', () => {
    before ('by changing the data', () =>{
        cy.visit('http://localhost:3001')
        cy.get('#add-contact').click()
        cy.get('#name').type('Emma')
        cy.get('#email').type('emma@mail.com')
        cy.get('#phone').type('070 1234567')
        cy.get('#company').type('Craf Academy')
        cy.get('#notes').type('Struggling noob coder')
        cy.get('#twitter').type('@emma')
        cy.get('#submit').click()
        cy.wait(500)
        cy.get('#update-button').click()
        cy.get('#name').clear()
        cy.type('Daniel')
        cy.get('#name').contain('should', 'Daniel')
    })
})